// Bilingual strings dictionary (English / Urdu)
const strings = {
  en: {
    home: 'Home',
    shop: 'Shop',
    cart: 'Cart',
    checkout: 'Checkout',
    admin: 'Admin',
    all_categories: 'All Categories',
    add_to_cart: 'Add to Cart',
    price: 'Price',
    stock: 'In Stock',
    out_of_stock: 'Out of Stock',
    featured_products: 'Featured Helmets',
    view_details: 'View Details',
    your_cart: 'Your Cart',
    product: 'Product',
    quantity: 'Quantity',
    total: 'Total',
    remove: 'Remove',
    update: 'Update Cart',
    proceed_checkout: 'Proceed to Checkout',
    empty_cart: 'Your cart is empty.',
    continue_shopping: 'Continue Shopping',
    full_name: 'Full Name',
    phone_number: 'Phone Number',
    address: 'Address',
    city: 'City',
    place_order: 'Place Order (Cash on Delivery)',
    order_success_title: 'Order Placed Successfully!',
    order_success_msg: 'Thank you for your order. Our team will contact you soon to confirm delivery.',
    order_id: 'Order ID',
    grand_total: 'Grand Total',
    payment_method: 'Payment Method',
    cod: 'Cash on Delivery',
    dark_mode: 'Dark Mode',
    search: 'Search helmets...',
    no_products: 'No products found in this category.',
    description: 'Description',
    related_products: 'You may also like',
    site_tagline: 'Ride Safe, Ride Smart',
    happy_customers: 'Happy Customers',
    helmet_models: 'Helmet Models',
    cities_covered: 'Cities Covered',
    years_experience: 'Years of Trust',
    faq_title: 'Frequently Asked Questions',
    faq: [
      { q: 'Do you offer Cash on Delivery?', a: 'Yes! All orders are Cash on Delivery (COD). You pay when the helmet reaches your doorstep — no advance payment needed.' },
      { q: 'How long does delivery take?', a: 'Delivery usually takes 2-5 business days depending on your city. Major cities are faster, remote areas may take a bit longer.' },
      { q: 'Can I return or exchange a helmet?', a: 'Yes, if the helmet is unused and in original packaging, you can request an exchange within 3 days of delivery. Contact us on the number in the footer.' },
      { q: 'Are the helmets certified for safety?', a: 'Our full face and modular helmets are DOT certified. Always check the product description for specific certification details.' },
      { q: 'How do I know my helmet size?', a: 'Measure around your head just above your eyebrows in centimeters, then check the size chart on the product page or contact us for guidance.' }
    ],
    back_to_top: 'Back to top',
    promo_title: 'Welcome to our store! 🪖',
    promo_msg: 'Free delivery on orders above Rs. 5000. Cash on Delivery available everywhere!',
    promo_close: 'Got it, thanks!',
    faq_link: 'FAQs',
    page_not_found: 'Page Not Found',
    page_not_found_msg: 'Looks like this helmet rode off somewhere else. Let\'s get you back on track.',
    go_home: 'Go to Homepage',
    // Breadcrumbs
    breadcrumb_home: 'Home',
    // Tabs
    tab_description: 'Description',
    tab_specs: 'Specifications',
    tab_reviews: 'Reviews',
    specs_material: 'Material',
    specs_material_val: 'ABS Shell with EPS foam liner',
    specs_weight: 'Weight',
    specs_weight_val: 'Approx. 1.4 kg',
    specs_certification: 'Certification',
    specs_certification_val: 'DOT Certified',
    specs_warranty: 'Warranty',
    specs_warranty_val: '6 Months',
    // Reviews
    write_review: 'Write a Review',
    your_rating: 'Your Rating',
    your_name: 'Your Name',
    your_review: 'Your Review',
    submit_review: 'Submit Review',
    no_reviews: 'No reviews yet. Be the first to review!',
    based_on_reviews: 'based on {n} reviews',
    // Checkout stepper
    step_cart: 'Cart Review',
    step_shipping: 'Shipping Details',
    step_confirm: 'Confirm Order',
    next: 'Next',
    back: 'Back',
    placing_order: 'Placing order...',
    // Toasts
    toast_added_cart: 'Added to cart!',
    toast_order_placed: 'Order placed successfully!',
    toast_login_success: 'Login successful!',
    toast_signup_success: 'Account created successfully!',
    toast_message_sent: 'Message sent! We will contact you soon.',
    // Login / Signup
    login_title: 'Login to Your Account',
    signup_title: 'Create an Account',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    remember_me: 'Remember me',
    login_btn: 'Login',
    no_account: 'Don\'t have an account?',
    signup_link: 'Sign up',
    have_account: 'Already have an account?',
    login_link: 'Login',
    date_of_birth: 'Date of Birth',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    newsletter_signup: 'Subscribe to newsletter for offers',
    agree_terms: 'I agree to the Terms & Conditions',
    signup_btn: 'Create Account',
    verify_otp_title: 'Verify Your Phone',
    verify_otp_msg: 'Enter the 6-digit code sent to your phone',
    verify_btn: 'Verify & Continue',
    resend_otp: 'Resend Code',
    demo_otp_note: 'Demo mode: your code is',
    // Contact
    contact_title: 'Contact Us',
    contact_msg: 'Have a question? Send us a message and we will get back to you.',
    message_label: 'Message',
    send_message: 'Send Message',
    // Password strength
    pwd_weak: 'Weak',
    pwd_medium: 'Medium',
    pwd_strong: 'Strong',
    // Pagination
    page: 'Page',
    of: 'of',
    load_more: 'Load More',
    loading: 'Loading...',
    // FAB / WhatsApp
    chat_whatsapp: 'Chat on WhatsApp',
    // Price filter
    price_range: 'Price Range',
    skip_to_content: 'Skip to content',
    shipping_returns_care: 'Shipping, Returns & Care',
    shipping_title: 'Shipping',
    shipping_desc: 'Cash on Delivery across Pakistan. Orders are dispatched within 24 hours and delivered in 2-5 business days depending on your city.',
    returns_title: 'Returns',
    returns_desc: 'Not satisfied? Return or exchange any unused helmet in original packaging within 3 days of delivery. No questions asked.',
    care_title: 'Helmet Care',
    care_desc: 'Clean the shell with a soft damp cloth, remove the inner padding to wash separately, and store away from direct sunlight to extend helmet life.'
  },
  ur: {
    home: 'ہوم',
    shop: 'شاپ',
    cart: 'کارٹ',
    checkout: 'چیک آؤٹ',
    admin: 'ایڈمن',
    all_categories: 'تمام اقسام',
    add_to_cart: 'کارٹ میں شامل کریں',
    price: 'قیمت',
    stock: 'دستیاب ہے',
    out_of_stock: 'دستیاب نہیں',
    featured_products: 'نمائشی ہیلمٹس',
    view_details: 'تفصیلات دیکھیں',
    your_cart: 'آپ کا کارٹ',
    product: 'پروڈکٹ',
    quantity: 'مقدار',
    total: 'ٹوٹل',
    remove: 'ہٹائیں',
    update: 'کارٹ اپڈیٹ کریں',
    proceed_checkout: 'چیک آؤٹ کریں',
    empty_cart: 'آپ کا کارٹ خالی ہے۔',
    continue_shopping: 'شاپنگ جاری رکھیں',
    full_name: 'پورا نام',
    phone_number: 'فون نمبر',
    address: 'ایڈریس',
    city: 'شہر',
    place_order: 'آرڈر کریں (کیش آن ڈیلیوری)',
    order_success_title: 'آرڈر کامیابی سے ہو گیا!',
    order_success_msg: 'آرڈر کرنے کا شکریہ۔ ہماری ٹیم ڈیلیوری کنفرم کرنے کے لیے آپ سے رابطہ کرے گی۔',
    order_id: 'آرڈر آئی ڈی',
    grand_total: 'کل رقم',
    payment_method: 'ادائیگی کا طریقہ',
    cod: 'کیش آن ڈیلیوری',
    dark_mode: 'ڈارک موڈ',
    search: 'ہیلمٹ تلاش کریں...',
    no_products: 'اس کیٹیگری میں کوئی پروڈکٹ نہیں ملا۔',
    description: 'تفصیل',
    related_products: 'یہ بھی پسند آ سکتے ہیں',
    site_tagline: 'محفوظ سفر، ذہین سفر',
    happy_customers: 'خوش گاہک',
    helmet_models: 'ہیلمٹ ماڈلز',
    cities_covered: 'شہر جہاں ڈیلیوری ہے',
    years_experience: 'سالوں کا اعتماد',
    faq_title: 'اکثر پوچھے گئے سوالات',
    faq: [
      { q: 'کیا آپ کیش آن ڈیلیوری دیتے ہیں؟', a: 'جی ہاں! تمام آرڈرز کیش آن ڈیلیوری (COD) پر ہیں۔ آپ ہیلمٹ ملنے پر ادائیگی کریں گے — کوئی ایڈوانس پیسے نہیں۔' },
      { q: 'ڈیلیوری میں کتنا وقت لگتا ہے؟', a: 'ڈیلیوری میں عام طور پر 2-5 دن لگتے ہیں، شہر کے حساب سے۔ بڑے شہروں میں جلدی، دور دراز علاقوں میں تھوڑا وقت لگ سکتا ہے۔' },
      { q: 'کیا میں ہیلمٹ واپس یا تبدیل کر سکتا ہوں؟', a: 'جی ہاں، اگر ہیلمٹ استعمال نہ ہوا ہو اور اصل پیکنگ میں ہو تو ڈیلیوری کے 3 دن کے اندر تبدیل کر سکتے ہیں۔ فوٹر میں دیے نمبر پر رابطہ کریں۔' },
      { q: 'کیا ہیلمٹس سیفٹی سرٹیفائیڈ ہیں؟', a: 'ہمارے فل فیس اور موڈیولر ہیلمٹس DOT سرٹیفائیڈ ہیں۔ تفصیلات پروڈکٹ کی تفصیل میں چیک کریں۔' },
      { q: 'میں اپنا ہیلمٹ سائز کیسے معلوم کروں؟', a: 'اپنے سر کے گرد بھنووں کے اوپر سینٹی میٹر میں پیمائش کریں، پھر پروڈکٹ پیج پر سائز چارٹ دیکھیں یا ہم سے رابطہ کریں۔' }
    ],
    back_to_top: 'اوپر جائیں',
    promo_title: 'ہمارے اسٹور میں خوش آمدید! 🪖',
    promo_msg: 'روپے 5000 سے زیادہ آرڈر پر مفت ڈیلیوری۔ کیش آن ڈیلیوری ہر جگہ دستیاب ہے!',
    promo_close: 'ٹھیک ہے، شکریہ!',
    faq_link: 'سوالات',
    page_not_found: 'صفحہ نہیں ملا',
    page_not_found_msg: 'لگتا ہے یہ ہیلمٹ کہیں اور چلا گیا۔ آئیں آپ کو واپس لے چلیں۔',
    go_home: 'ہوم پیج پر جائیں',
    breadcrumb_home: 'ہوم',
    tab_description: 'تفصیل',
    tab_specs: 'خصوصیات',
    tab_reviews: 'ریویوز',
    specs_material: 'میٹریل',
    specs_material_val: 'ABS شیل اور EPS فوم لائنر',
    specs_weight: 'وزن',
    specs_weight_val: 'تقریباً 1.4 کلوگرام',
    specs_certification: 'سرٹیفیکیشن',
    specs_certification_val: 'DOT سرٹیفائیڈ',
    specs_warranty: 'وارنٹی',
    specs_warranty_val: '6 مہینے',
    write_review: 'ریویو لکھیں',
    your_rating: 'آپ کی ریٹنگ',
    your_name: 'آپ کا نام',
    your_review: 'آپ کا ریویو',
    submit_review: 'ریویو جمع کریں',
    no_reviews: 'ابھی کوئی ریویو نہیں۔ پہلا ریویو آپ لکھیں!',
    based_on_reviews: '{n} ریویوز کی بنیاد پر',
    step_cart: 'کارٹ چیک کریں',
    step_shipping: 'شپنگ تفصیلات',
    step_confirm: 'آرڈر کنفرم کریں',
    next: 'اگلا',
    back: 'پیچھے',
    placing_order: 'آرڈر ہو رہا ہے...',
    toast_added_cart: 'کارٹ میں شامل ہو گیا!',
    toast_order_placed: 'آرڈر کامیابی سے ہو گیا!',
    toast_login_success: 'لاگ ان کامیاب ہوا!',
    toast_signup_success: 'اکاؤنٹ کامیابی سے بن گیا!',
    toast_message_sent: 'پیغام بھیج دیا گیا! ہم جلد رابطہ کریں گے۔',
    login_title: 'اپنے اکاؤنٹ میں لاگ ان کریں',
    signup_title: 'اکاؤنٹ بنائیں',
    email: 'ای میل',
    password: 'پاس ورڈ',
    confirm_password: 'پاس ورڈ دوبارہ لکھیں',
    remember_me: 'مجھے یاد رکھیں',
    login_btn: 'لاگ ان',
    no_account: 'اکاؤنٹ نہیں ہے؟',
    signup_link: 'اکاؤنٹ بنائیں',
    have_account: 'پہلے سے اکاؤنٹ ہے؟',
    login_link: 'لاگ ان کریں',
    date_of_birth: 'تاریخ پیدائش',
    gender: 'جنس',
    male: 'مرد',
    female: 'عورت',
    newsletter_signup: 'آفرز کے لیے نیوز لیٹر سبسکرائب کریں',
    agree_terms: 'میں شرائط و ضوابط سے متفق ہوں',
    signup_btn: 'اکاؤنٹ بنائیں',
    verify_otp_title: 'اپنا فون تصدیق کریں',
    verify_otp_msg: 'اپنے فون پر بھیجا گیا 6 ہندسوں کا کوڈ درج کریں',
    verify_btn: 'تصدیق کریں اور آگے بڑھیں',
    resend_otp: 'کوڈ دوبارہ بھیجیں',
    demo_otp_note: 'ڈیمو موڈ: آپ کا کوڈ ہے',
    contact_title: 'ہم سے رابطہ کریں',
    contact_msg: 'کوئی سوال ہے؟ ہمیں پیغام بھیجیں، ہم جلد جواب دیں گے۔',
    message_label: 'پیغام',
    send_message: 'پیغام بھیجیں',
    pwd_weak: 'کمزور',
    pwd_medium: 'درمیانہ',
    pwd_strong: 'مضبوط',
    page: 'صفحہ',
    of: 'از',
    load_more: 'مزید دکھائیں',
    loading: 'لوڈ ہو رہا ہے...',
    chat_whatsapp: 'واٹس ایپ پر بات کریں',
    price_range: 'قیمت کی حد',
    skip_to_content: 'مواد پر جائیں',
    shipping_returns_care: 'شپنگ، واپسی اور دیکھ بھال',
    shipping_title: 'شپنگ',
    shipping_desc: 'پورے پاکستان میں کیش آن ڈیلیوری۔ آرڈر 24 گھنٹوں میں بھیج دیا جاتا ہے اور شہر کے حساب سے 2-5 دن میں پہنچتا ہے۔',
    returns_title: 'واپسی',
    returns_desc: 'پسند نہیں آیا؟ کسی بھی غیر استعمال شدہ ہیلمٹ کو اصل پیکنگ میں ڈیلیوری کے 3 دن کے اندر واپس یا تبدیل کریں۔ کوئی سوال نہیں پوچھا جائے گا۔',
    care_title: 'ہیلمٹ کی دیکھ بھال',
    care_desc: 'شیل کو نرم گیلے کپڑے سے صاف کریں، اندر کی گدی الگ سے دھونے کے لیے نکالیں، اور دھوپ سے دور رکھیں تاکہ ہیلمٹ زیادہ دیر چلے۔'
  }
};

function langMiddleware(req, res, next) {
  let lang = req.cookies.lang || 'en';
  if (lang !== 'en' && lang !== 'ur') lang = 'en';

  res.locals.lang = lang;
  res.locals.dir = lang === 'ur' ? 'rtl' : 'ltr';
  res.locals.t = strings[lang];
  next();
}

module.exports = langMiddleware;
